### ISSUE TITLE
Build local transportation map

### ISSUE THREAD

**Issue by orchoban** [DataCyberDevelopment/ui-db---frontEnd#25]
Build local transportation map for English and Hebrew:

- [x] English 
- [x] Hebrew

**Comment by touhidbd** [comment]
@orchoban I got the error when running this code. `$("body").innerText=JSON.stringify(mapTranslate)`

![image](https://user-images.githubusercontent.com/8915879/141984958-1ffeb656-c259-4912-bf37-b3bd30be5e26.png)

**Comment by orchoban** [comment]
> $("body").innerText=JSON.stringify(mapTranslate)

https://github.com/DataCyberDevelopment/ui-db---frontEnd/commit/7b166537b948ec968ccacd0830aad082eae8cf3d#r60360895

@touhidbd  you don't need to do it.
This issue I assignees

**Comment by orchoban** [comment]
@touhidbd done, 
I make it for Hebrew and for English 
https://github.com/DataCyberDevelopment/ui-db---frontEnd/commit/4e294d162cbf648b529861ce0cc02d687c99aef4
