### ISSUE TITLE
Illustration LTR and RTL

### ISSUE THREAD

**Issue by orchoban** [DataCyberDevelopment/ui-db---frontEnd#39]
![image](https://user-images.githubusercontent.com/33927385/140294945-adfaf852-9ca6-4bfb-a588-8d2d19bdbb95.png)

This part have illustrations for rtl version and for ltr version.

xd RTL:
![image](https://user-images.githubusercontent.com/33927385/140295259-2182e84a-811d-4ac7-bb11-d207c3d8231a.png)

xd LTR:
![image](https://user-images.githubusercontent.com/33927385/140295303-c2f4711d-49a5-44a5-ac96-1528c3ec37c2.png)

Please make code like:
``` src={props.i18n.dir() === "rtl"?RtlImage:LtrImage} ```

**Comment by touhidbd** [comment]
Fixed it with CSS

**Comment by touhidbd** [comment]
Solved
