### ISSUE TITLE
header hebrew tabs need full width

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#43]
header - menu tabs needs full width. 

on site
<img width="627" alt="Screen Shot 2021-11-25 at 10 51 52" src="https://user-images.githubusercontent.com/95017644/143409972-eca58ef8-22bc-4a2b-b443-c77dde36d791.png">

on xd-design
<img width="538" alt="Screen Shot 2021-11-25 at 10 56 37" src="https://user-images.githubusercontent.com/95017644/143410507-98e67a6d-d8fb-4383-a9a6-c13614432181.png">

**Comment by touhidbd** [comment]
Solved
