### ISSUE TITLE
images need to be centered correctly - hebrew & english

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#44]
1. use the original assets dx-design - hebrew and english
2. it needs to be mirrored in hebrew ("?", "v", "hello" are the same in hebrew and english)

on pages - home, about us, our projects

<img width="870" alt="Screen Shot 2021-11-25 at 11 11 30" src="https://user-images.githubusercontent.com/95017644/143414534-ee95c52a-19f2-4c96-b82f-3674545f401d.png">

**Comment by touhidbd** [comment]
Solved
