### ISSUE TITLE
button need to be added - hebrew & english

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#47]
missing "more articles" button - add the button as it presented on the dx-design - hebrew and english 

on site
<img width="864" alt="Screen Shot 2021-11-25 at 11 57 55" src="https://user-images.githubusercontent.com/95017644/143420258-9b2c6dc3-e8d6-4151-a187-7ce0250846a5.png">

on dx-design
<img width="480" alt="Screen Shot 2021-11-25 at 11 57 17" src="https://user-images.githubusercontent.com/95017644/143420309-60690825-52b1-4e0e-95d2-aa556b6f2ba6.png">

**Comment by touhidbd** [comment]
Solved
