### ISSUE TITLE
Blog - navigation bar need to be changed - english & hebrew

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#48]
in the blog page, change the nevigation bar to be like in the original design - english and hebrew

on website
<img width="866" alt="Screen Shot 2021-11-25 at 12 52 40" src="https://user-images.githubusercontent.com/95017644/143429706-8f4eb3c9-aca5-4225-b032-92e53452df3d.png">

on dx-design
<img width="485" alt="Screen Shot 2021-11-25 at 12 52 58" src="https://user-images.githubusercontent.com/95017644/143429742-54628b29-f26c-4e03-b77d-d767d8b35d23.png">

**Comment by orchoban** [comment]
@touhidbd I changed it to `react-js-pagination` Please try to fix the style

**Comment by touhidbd** [comment]
Solved

**Comment by danasegal1** [comment]
👍
