### ISSUE TITLE
footer - text alignment

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#53]
the text at the end of "contact us" section is 'word-wrap: break-word'. align it so it will start from the same spot on every row

<img width="1046" alt="Screen Shot 2021-11-25 at 15 01 36" src="https://user-images.githubusercontent.com/95017644/143446463-47de4fdb-55d3-49e8-b54e-8f28f9ccc261.png">

wanted
<img width="1029" alt="Screen Shot 2021-11-25 at 15 12 34" src="https://user-images.githubusercontent.com/95017644/143447935-8adf3750-175d-436e-aba3-1998b694f0c5.png">

**Comment by touhidbd** [comment]
Sovled

**Comment by danasegal1** [comment]
thank you (:
