### ISSUE TITLE
our projects page - text mixing with background

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#55]
on the second level of the ״our projects״ page the text and the background have the same colour, so the text can't be read.

<img width="737" alt="Screen Shot 2021-11-28 at 12 01 06" src="https://user-images.githubusercontent.com/95017644/143763546-eb5adb94-55c2-4e9d-afcb-814b7a0b5d51.png">

<img width="684" alt="Screen Shot 2021-11-28 at 12 01 16" src="https://user-images.githubusercontent.com/95017644/143763541-28b27f25-6764-4bb8-bead-1876bc7c21d2.png">

**Comment by touhidbd** [comment]
@danasegal1 Solved.
