### ISSUE TITLE
our project items - image slider need max width and height

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#56]
please give max width and height, maybe try to use backgruond-image

you can see example on `/our-projects/156`

<img width="606" alt="Screen Shot 2021-11-28 at 12 00 22" src="https://user-images.githubusercontent.com/95017644/143763690-641873e9-4c23-45f8-90a7-f9e936b9841b.png">

<img width="566" alt="Screen Shot 2021-11-28 at 12 00 40" src="https://user-images.githubusercontent.com/95017644/143763696-2f0d1963-32fc-4a81-aeec-82d00bdca3cd.png">

**Comment by danasegal1** [comment]
<img width="783" alt="Screen Shot 2021-11-30 at 10 12 37" src="https://user-images.githubusercontent.com/95017644/144009868-e38087c0-73c0-40fb-a8fb-87c3bd06ddf1.png">

**Comment by touhidbd** [comment]
Solved
