### ISSUE TITLE
CustomerSupport new Lottie

### ISSUE THREAD

**Issue by orchoban** [DataCyberDevelopment/ui-db---frontEnd#61]
I replaced the image to new lottie, please try to fit it our site
![image](https://user-images.githubusercontent.com/33927385/144016665-88a7bbe5-7678-4364-9692-c1b93c802d30.png)
![image](https://user-images.githubusercontent.com/33927385/144016732-4671480c-8955-4d4a-aac4-f2915838ce10.png)

**Comment by touhidbd** [comment]
Solved

**Comment by orchoban** [comment]
Thanx!

Please see issue on mobile:
![image](https://user-images.githubusercontent.com/33927385/144047387-80367f6f-9556-4257-b575-c113c1c7d2ae.png)
![image](https://user-images.githubusercontent.com/33927385/144047460-43995037-fc8a-46de-8e6c-62421ea48be0.png)

It is look like `border`, but it is not.

**Comment by touhidbd** [comment]
@orchoban Actually, this is no issue. If you check with 100% view you will see there are no borders.

![image](https://user-images.githubusercontent.com/8915879/144051785-be48db23-db4f-40b0-8c4d-94977f49da26.png)

**Comment by orchoban** [comment]
Great
