### ISSUE TITLE
out projects page -  the first image on wordpress needs to be shown first on site

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#62]
the first image shown on the site is the last one in the wordpress. the second image shown on site is the one that needed to be first. it means that the order is correct but the first image shown on site is wrong, it need to be the first as defined on wordpress - both english and hebrew sites.
example: our-projects/155

first on site now
<img width="517" alt="Screen Shot 2021-11-30 at 11 53 08" src="https://user-images.githubusercontent.com/95017644/144026752-8fce627c-ada5-4407-9e08-5b91f05cf4cf.png">

last on wordpress
<img width="331" alt="Screen Shot 2021-11-30 at 11 55 01" src="https://user-images.githubusercontent.com/95017644/144027042-958354bc-ab3d-46b9-aaa4-498fafd96f5d.png">

first on wordpress - should be first on site but it is second
<img width="400" alt="Screen Shot 2021-11-30 at 11 55 16" src="https://user-images.githubusercontent.com/95017644/144027288-1f0d8344-07c1-4f71-b0ee-dad44b35c1de.png">

**Comment by touhidbd** [comment]
@orchoban I think this is actually a query issue. Could you please check it?

**Comment by orchoban** [comment]
@touhidbd 

![image](https://user-images.githubusercontent.com/33927385/144049284-58dd9850-a2fb-46da-8050-ccd987679097.png)
![image](https://user-images.githubusercontent.com/33927385/144049986-df4874d6-9944-4547-a174-c00d6a42bbe5.png)
![image](https://user-images.githubusercontent.com/33927385/144050040-f8d28092-bd32-4d32-8b12-f970b3ec21e2.png)

**Comment by orchoban** [comment]
Yes, I solved it for English with:
https://stackoverflow.com/questions/56438595/react-slick-slider-items-are-miss-ordered-first-item-is-rendered-as-last-items

But still problem with Hebrew, Let me check

**Comment by orchoban** [comment]
solved
