### ISSUE TITLE
change text on header

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#68]
LTR :change from 'Home' to 'Home Page'
![image](https://user-images.githubusercontent.com/95017644/147678186-284b0f28-a17f-4c39-987a-7e418447f7f2.png)

RTL: 
change from 'בית' to 'דף הבית' 
![image](https://user-images.githubusercontent.com/95017644/147678259-aa027de0-2b78-45f6-a2ad-bd18cd1edc70.png)

change from 'עלינו' to 'אודותינו'
![image](https://user-images.githubusercontent.com/95017644/147678313-e9fc6607-d0f3-4fda-9f5a-9b7232b7e39e.png)

**Comment by touhidbd** [comment]
Update

**Comment by orchoban** [comment]
Thank you Touhid.
@danasegal1 next time, for Hebrew issue tag someone from Israel.
